handlebars.cache: true
# Hibernate ddl auto (create, create-drop, update)
spring:
   - jpa:
     generate-ddl: true
     database-platform : org.hibernate.dialect.MySQL5Dialect
     hibernate:
       ddl-auto: update
